[package]
name = "hello-web"
version = "0.1.0"
authors = ["Alexandre Nunes <alexandrenunes@poli.ufrj.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
